# Generated by Django 5.2 on 2025-07-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('planning', 'Planning'), ('on hold', 'On hold'), ('completed', 'Completed')], default='Planning', max_length=20),
        ),
    ]
